config/routes.rb
Rails.application.routes.draw do

  get 'appearances/new/:public_uid' => 'appearances#new',as:'appearance'
  post 'appearances/create' => 'appearances#create'
  get 'appearances/recommend' => 'appearances#recommend'
  get 'top' => 'posts#top', as: 'top'

  
  devise_for :users
  
  resources :posts do
    member do
      get :top
    end 
  end

  get 'users/show' => 'users#show' ,as: 'user'
  resources :users
  
  root"posts#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appearance.rb
class Appearance < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  generate_public_uid
  has_many :posts
  has_many :appearances

  def to_param
    public_uid
  end
end

app/controllers/appearances_controller.rb
class AppearancesController < ApplicationController
  before_action :set_appearance, only: %i[ show edit update destroy ]

  
  # GET /appearances/new
  def new
    @appearance = Appearance.new
    @user = User.find_by(public_uid: params[:public_uid])
  end

  # GET /appearances/1/edit
  def edit
  end

  # POST /appearances or /appearances.json
  def create
    @appearance = Appearance.new(appearance_params)


      if @appearance.save
        redirect_to top_path
      else
        #redirect_to appearance_craete_path(params[:public_uid])
        redirect_to user_path
      end

  end

  # PATCH/PUT /appearances/1 or /appearances/1.json
  def update
    respond_to do |format|
      if @appearance.update(appearance_params)
        format.html { redirect_to appearance_url(@appearance), notice: "Appearance was successfully updated." }
        format.json { render :show, status: :ok, location: @appearance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appearance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appearances/1 or /appearances/1.json
  def destroy
    @appearance.destroy

    respond_to do |format|
      format.html { redirect_to appearances_url, notice: "Appearance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appearance
      @appearance = Appearance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appearance_params
      params.require(:appearance).permit(:first, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten, :eleven, :twelve, :thirteen, :fourteen, :fifteen, :sixteen, :seventeen, :eighteen, :nineteen, :twenty, :user_id, :public_uid)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :top
  before_action :set_post, only: %i[ show edit update destroy ]

  def top
    @users = User.find(6, 7)
  end

  # GET /posts or /posts.json
  def index
    @user = current_user
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id

    if @post.save
      redirect_to user_path
    else
      redirect_to user_path
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :first, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten, :eleven, :twelve, :thirteen, :fourteen, :fifteen, :sixteen, :seventeen, :eighteen, :nineteen, :twenty)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def show
        @user = User.find_by(id: current_user.id)
    end
end

app/helpers/appearances_helper.rb
module AppearancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appearances/edit.html.erb
<h1>Editing Appearance</h1>

<%= render 'form', appearance: @appearance %>

<%= link_to 'Show', @appearance %> |
<%= link_to 'Back', appearances_path %>

app/views/appearances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @appearance.first %>
</p>

<p>
  <strong>Two:</strong>
  <%= @appearance.two %>
</p>

<p>
  <strong>Three:</strong>
  <%= @appearance.three %>
</p>

<p>
  <strong>Four:</strong>
  <%= @appearance.four %>
</p>

<p>
  <strong>Five:</strong>
  <%= @appearance.five %>
</p>

<p>
  <strong>Six:</strong>
  <%= @appearance.six %>
</p>

<p>
  <strong>Seven:</strong>
  <%= @appearance.seven %>
</p>

<p>
  <strong>Eight:</strong>
  <%= @appearance.eight %>
</p>

<p>
  <strong>Nine:</strong>
  <%= @appearance.nine %>
</p>

<p>
  <strong>Ten:</strong>
  <%= @appearance.ten %>
</p>

<p>
  <strong>Eleven:</strong>
  <%= @appearance.eleven %>
</p>

<p>
  <strong>Twelve:</strong>
  <%= @appearance.twelve %>
</p>

<p>
  <strong>Thirteen:</strong>
  <%= @appearance.thirteen %>
</p>

<p>
  <strong>Fourteen:</strong>
  <%= @appearance.fourteen %>
</p>

<p>
  <strong>Fifteen:</strong>
  <%= @appearance.fifteen %>
</p>

<p>
  <strong>Sixteen:</strong>
  <%= @appearance.sixteen %>
</p>

<p>
  <strong>Seventeen:</strong>
  <%= @appearance.seventeen %>
</p>

<p>
  <strong>Eighteen:</strong>
  <%= @appearance.eighteen %>
</p>

<p>
  <strong>Nineteen:</strong>
  <%= @appearance.nineteen %>
</p>

<p>
  <strong>Twenty:</strong>
  <%= @appearance.twenty %>
</p>

<p>
  <strong>User:</strong>
  <%= @appearance.user_id %>
</p>

<%= link_to 'Edit', edit_appearance_path(@appearance) %> |
<%= link_to 'Back', appearances_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Chart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>post</h1>

<%= current_user.email %>

<canvas id="myChart"></canvas>
<script>

var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
  type: 'radar',
  data: {
    labels: ["D", "I", "S", "C"],
    datasets: 
    [
      <% @dsum = @user.posts.sum(:four) + @user.posts.sum(:seven) + @user.posts.sum(:seventeen) + @user.posts.sum(:nineteen) + @user.posts.sum(:twenty) %>// カラムのデータの合計値
      <% @dcount=@user.posts.count(:created_at) %> 

      <% @isum = @user.posts.sum(:six) + @user.posts.sum(:eight) + @user.posts.sum(:eleven) + @user.posts.sum(:fourteen) +  @user.posts.sum(:two) %>// カラムのデータの合計値
      <% @icount=@user.posts.count(:created_at) %>

      <% @ssum = @user.posts.sum(:three) + @user.posts.sum(:nine) + @user.posts.sum(:thirteen) + @user.posts.sum(:sixteen) + @user.posts.sum(:eighteen) %>// カラムのデータの合計値
      <% @scount=@user.posts.count(:created_at) %>

      <% @csum = @user.posts.sum(:first) + @user.posts.sum(:five) + @user.posts.sum(:ten) + @user.posts.sum(:twelve) + @user.posts.sum(:fifteen) %>// カラムのデータの合計値
      <% @ccount=@user.posts.count(:created_at) %>
        {
        label: "テスト",
        backgroundColor: 'rgba(122,255,129,0.2)',
        borderColor: '#000',
        data: [<%= @dsum.to_f/@dcount %>, <%= @isum.to_f/@icount %>, <%= @ssum.to_f/@scount %>, <%= @csum.to_f/@ccount %>]
        },
    ]
  },
  options: {
      scale: {
          ticks: {
              suggestedMin: 0,
              suggestedMax: 5
          }
      }
  }
});

</script>

<br>

<% if user_signed_in? %>
  <%= button_to "マイページへ",  user_path,method: :get,class:'btn btn-dark' %>
<% end %>

<%= link_to 'New Post', new_post_path %>

<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>

<% if user_signed_in? && current_user.admin? %>
    <h4>Adminですよ</h4>
    <h4>User.create!(name:  "kazuya", email: "kazuya@mail.com", password:  "ochibi", password_confirmation: "ochibi", admin: true)
<% end %>

app/views/posts/new.html.erb
<div class="zentai">
    <h1>自己分析</h1><br>

    <%= render 'form', post: @post %>

    <%= link_to 'トップページへ', top_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/top.html.erb
<% if user_signed_in? %>
    <%= button_to "マイページへ",  user_path,method: :get,class:'btn btn-dark' %>
<% else %>
    <%= button_to "ログイン",  new_user_session_path,method: :get,class:'btn btn-dark' %>
<% end %>
<div class = "box1">
    <h1>他己分析をオンラインで行おう</h1><br>
    <p>コロナ禍は中々対面で自己分析を手伝ってもらうことが出来ない</p>
    <p>このサイトではまず自分で自己分析の一種であるDISC診断を行い、周りの人にも自分のことを診断してもらうことが可能です</p>
    <p>診断後にはマイページで自分と他社の回答を視覚化して比較が出来ます</p>
</div>

<%  @users.each do |t|%>
    <%= t.id%>
<% end %>

<div class = "box2">
    <h1>DISC診断とは</h1><br>
    <p>「DiSC理論」とは、1920年代にアメリカのウィリアム・M・マーストン博士が提唱したコミュニケーション理論です。人の性格・特性や行動パターンを4つのタイプに分類し、各タイプ別に適切なコミュニケーション方法を導きだしています。</p><br>

    <h3>D（Dominance）：主導型とは</h3>	
    <ul>
        <li>責任感と自信があり、チャレンジ精神を持つタイプ</li>
        <li>一生懸命に物事に取り組み、迅速な結果を求める傾向がある</li>
    </ul>
    <br>

    <h3>i（influence）：感化型とは</h3>	
    <ul>
        <li>社交性があり楽観的なところが特徴で、組織内ではムードメーカーの役割を果たすタイプ</li>
        <li>発想が豊かであり、対人関係にも優れた能力を発揮する</li>
    </ul>
    <br>

    <h3>S（Steadiness）：安定型とは</h3>	
    <ul>
        <li>人への配慮ができ、協調性のあるタイプ</li>
        <li>ひとつの事柄を地道に遂行できる能力に長けており、仕事ぶりに安定感がある</li>
    </ul>
    <br>

    <h3>C（Conscientiousness）：慎重型とは</h3>	
    <ul>
        <li>論理的に考えることを得意としており、計画的に仕事を遂行する力を持つタイプ</li>
        <li>間違いのないように確認する慎重さを持ち合わせている
    </li>
    </ul>
</div>
<div class = "box1">
    <h1>このサイトの使い方</h1><br>
    <ul>
        <li><%= link_to "マイページ",  user_path %>で自己分析をする</li>
        <li><%= link_to "マイページ",  user_path %>下部のリンクを周りの人に送り、回答してもらう</li>
        <li>周りの人の回答の平均が表示される</li>
    </ul>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'users', :media => "all" %>

<div class ="box3" >
<h1>マイページ <%= @user.email %></h1><br>
<%= link_to 'トップページへ', top_path %><br>

<% if @user.posts.blank? %>
    <%= link_to '自己分析をする', new_post_path %>
<% end %>

<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<br>
    <div class ="box4" >
    <h1>まずは自己分析</h1>
        <canvas id="myChart" width="50%"></canvas>
        <script>
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
        type: 'radar',
        data: {
            labels: ["D型", "I型", "S型", "C型"],
            datasets: 
            [
            <% @dsum = @user.posts.sum(:four) + @user.posts.sum(:seven) + @user.posts.sum(:seventeen) + @user.posts.sum(:nineteen) + @user.posts.sum(:twenty) %>
            <% @dcount=@user.posts.count(:created_at) %> 

            <% @isum = @user.posts.sum(:six) + @user.posts.sum(:eight) + @user.posts.sum(:eleven) + @user.posts.sum(:fourteen) +  @user.posts.sum(:two) %>
            <% @icount=@user.posts.count(:created_at) %>

            <% @ssum = @user.posts.sum(:three) + @user.posts.sum(:nine) + @user.posts.sum(:thirteen) + @user.posts.sum(:sixteen) + @user.posts.sum(:eighteen) %>
            <% @scount=@user.posts.count(:created_at) %>

            <% @csum = @user.posts.sum(:first) + @user.posts.sum(:five) + @user.posts.sum(:ten) + @user.posts.sum(:twelve) + @user.posts.sum(:fifteen) %>
            <% @ccount=@user.posts.count(:created_at) %>
                {
                label: "自己分析",
                backgroundColor: 'rgba(122,255,129,0.2)',
                //borderColor: '#000',
                data: [<%= @dsum.to_f/@dcount %>, <%= @isum.to_f/@icount %>, <%= @ssum.to_f/@scount %>, <%= @csum.to_f/@ccount %>]
                },
            ]
        },
        options: {
            scale: {
                ticks: {
                    suggestedMin: 0,
                    suggestedMax: 20
                }
            }
        }
        });

        </script>
    </div>

    <br>


<% if @user.appearances.blank? %>
    <p>友達に診断してもらいたい人は</p>
    <p>以下のリンクをコピーして友達に診断してもらおう！</p>
        <textarea id="bar" readonly>
            <%# "#{user_url(public_uid: current_user.public_uid)}" %>
            <%= "#{appearance_url(public_uid: current_user.public_uid)}" %>
        </textarea>
        <br>
        <button onclick="copyToClipboard()">リンクをコピー</button><br>


        <script>
            function copyToClipboard() {
                // コピー対象をJavaScript上で変数として定義する
                var copyTarget = document.getElementById("bar");

                // コピー対象のテキストを選択する
                copyTarget.select();

                // 選択しているテキストをクリップボードにコピーする
                document.execCommand("Copy");

                alert("コピーしました! : " + copyTarget.value);
            }
        </script>

<% else %>

        <div class ="box2" >
            <h1>他己分析</h1>
                <canvas id="yourChart" width="50%"></canvas>
                <script>

                var ctx = document.getElementById("yourChart");
                var yourChart = new Chart(ctx, {
                type: 'radar',
                data: {
                    labels: ["D型", "I型", "S型", "C型"],
                    datasets: 
                    [
                    <% @dsum = @user.appearances.sum(:four) + @user.appearances.sum(:seven) + @user.appearances.sum(:seventeen) + @user.appearances.sum(:nineteen) + @user.appearances.sum(:twenty) %>
                    <% @dcount=@user.appearances.count(:created_at) %> 

                    <% @isum = @user.appearances.sum(:six) + @user.appearances.sum(:eight) + @user.appearances.sum(:eleven) + @user.appearances.sum(:fourteen) +  @user.appearances.sum(:two) %>
                    <% @icount=@user.appearances.count(:created_at) %>

                    <% @ssum = @user.appearances.sum(:three) + @user.appearances.sum(:nine) + @user.appearances.sum(:thirteen) + @user.appearances.sum(:sixteen) + @user.appearances.sum(:eighteen) %>
                    <% @scount=@user.appearances.count(:created_at) %>

                    <% @csum = @user.appearances.sum(:first) + @user.appearances.sum(:five) + @user.appearances.sum(:ten) + @user.appearances.sum(:twelve) + @user.appearances.sum(:fifteen) %>
                    <% @ccount=@user.appearances.count(:created_at) %>
                        {
                        label: "他己分析",
                        backgroundColor: 'rgba(122,255,129,0.2)',
                        //borderColor: '#000',
                        data: [<%= @dsum.to_f/@dcount %>, <%= @isum.to_f/@icount %>, <%= @ssum.to_f/@scount %>, <%= @csum.to_f/@ccount %>]
                        },
                    ]
                },
                options: {
                    scale: {
                        ticks: {
                            suggestedMin: 0,
                            suggestedMax: 20
                        }
                    }
                }
                });
                </script>
            </div>
        </div>

        <p>友達に診断してもらいたい人は</p>
    <p>以下のリンクをコピーして友達に診断してもらおう！</p>
        <textarea id="bar" readonly>
            <%# "#{user_url(public_uid: current_user.public_uid)}" %>
            <%= "#{appearance_url(public_uid: current_user.public_uid)}" %>
        </textarea>
        <br>
        <button onclick="copyToClipboard()">リンクをコピー</button><br>


        <script>
            function copyToClipboard() {
                // コピー対象をJavaScript上で変数として定義する
                var copyTarget = document.getElementById("bar");

                // コピー対象のテキストを選択する
                copyTarget.select();

                // 選択しているテキストをクリップボードにコピーする
                document.execCommand("Copy");

                alert("コピーしました! : " + copyTarget.value);
            }
        </script>
<% end %>

<%# link_to "post一覧に戻る", posts_path %>